services:
    invoicing.menu_builder:
        class: Jma\Invoicing\AppBundle\Menu\MenuBuilder
        arguments:
            - "@knp_menu.factory"
            - "@security.context"            

    invoicing.frontend_menu:
        class: Knp\Menu\MenuItem
        factory_service: invoicing.menu_builder
        factory_method: createMainMenu
        arguments: ["@request"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: frontendNavbar }
            
    invoicing.frontend_dropdown_menu:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: invoicing.menu_builder
        factory_method: createDropdownMenu
        arguments: ["@request"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: frontendRightNavbar }