services:
    invoicing.frontend.navbar:
        class: %mopa_bootstrap.navbar.generic%
        arguments:
            # first argument: a named array of menues:
            - { leftmenu: "@invoicing.frontend_menu=", rightmenu: "@invoicing.frontend_dropdown_menu=" }
            # second argument: a named array of FormType Classes  
            - { }
            # third argument: a named array of options
            - { title: "SAV", titleRoute: "homepage", fixedTop: true }
        tags:
            # The alias is used to retrieve the navbar in templates
            - { name: mopa_bootstrap.navbar, alias: frontendNavbar }
      
    invoicing.menu_builder:
        class: Jma\Invoicing\AppBundle\Menu\MenuBuilder
        arguments:
            - "@knp_menu.factory"
            - "@security.context"            

    invoicing.frontend_menu:
        class: Knp\Menu\MenuItem
        factory_service: invoicing.menu_builder
        factory_method: createMainMenu
        arguments: ["@request"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: frontendNavbar }
            
    invoicing.frontend_dropdown_menu:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: invoicing.menu_builder
        factory_method: createDropdownMenu
        arguments: ["@request"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: frontendRightNavbar }