invoicing_client:
    resource: "@InvoicingAppBundle/Resources/config/routing/client.yml"

invoicing_entrepreneur:
    resource: "@InvoicingAppBundle/Resources/config/routing/entrepreneur.yml"

invoicing_invoice:
    resource: "@InvoicingAppBundle/Resources/config/routing/invoice.yml"

invoicing_tag:
    resource: "@InvoicingAppBundle/Resources/config/routing/tag.yml"
    
invoicing_security_login:
    pattern: /login
    defaults:
        _controller: InvoicingAppBundle:Security:login
        
invoicing_security_login_check:
    pattern: /login_check
    defaults:
        _controller: InvoicingAppBundle:Security:check
        
invoicing_security_logout:
    pattern: /logout
    defaults:
        _controller: InvoicingAppBundle:Security:logout