invoicing_app:
    users:
        admin: { password: d033e22ae348aeb5660fc2140aec35850c4da997, roles: [ROLE_SUPER_ADMIN] }
        josephmaarek: { password: 13de8889aecf8f48d9c799a1f3fb520fa748372a, roles: [ROLE_ENTREPRENEUR] }
        josephmaarek_16: { password: 13de8889aecf8f48d9c799a1f3fb520fa748372a, roles: [ROLE_ENTREPRENEUR] }