imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
        #firephp:
        #    type:  firephp
        #    level: debug
        #chromephp:
        #    type:  chromephp
        #    level: debug

doctrine:
    dbal:
        dbname:   %database_name%_test

assetic:
    use_controller: true
    
bazinga_faker:
    orm: doctrine
    locale: fr_FR
    entities:
        Jma\Invoicing\AppBundle\Entity\Client:
            number: 50
            custom_formatters:
                raisonSociale: { method: company }
                telephone: { method: phoneNumber }
                mobile: { method: phoneNumber }
                fax: { method: phoneNumber }
                signataire: { method: name }
                adresse: { method: streetAddress }
                web: { method: url }
                ville: { method: city }
                codePostal: { method: postCode }
                complementAdresse:  { method: randomElement, parameters: [ [ null ] ] }

swiftmailer:
    delivery_address:  josephmaarek@gmail.com

services:
    twig.extension.debug:
        class: Twig_Extensions_Extension_Debug
        tags:
            - { name: twig.extension }
