parameters:
    html2pdf.orientation: P
    html2pdf.format: A4
    html2pdf.lang: fr

    html2pdf.unicode: true
    html2pdf.encoding: 'UTF-8'
    html2pdf.margin: [5, 5, 5, 0]

    sav:
        styles: [ aj, md, rk ]
        md:
            mail_sender:                    "contact@maisondevis.com"
            mail_reply_to:                  "maisonetdevis@gmail.com"
            mail_receiver_cc:               "maisonetdevis@gmail.com"
            object_mail:
                bon_de_commande:            "BDC maison et devis"
                facture:                    "Facture maison et devis"
                facture_proforma:           "Facture PF maison et devis"
            options:
                options1_label: Format
                options1_width: 88mm
                options1_property: format

                options2_label: Activites
                options2_width: 58mm
                options2_property: activites

                options3_label: Departement
                options3_width: 161mm
                options3_property: departement

            header_facture: |
              <p>
                <b>MAISON ET DEVIS</b><br />
                CAP ST ANTOINE<br />
                155 RUE DE ROSNY<br />
                93100 MONTREUIL<br />
              </p>
              <p>
                <b>Tél:</b>      01.43.60.97.50<br />
                <b>Fax:</b>      01.43.60.97.50<br />
                <b>Capital:</b>  7 500 Euros<br />
                <b>R.C.S:</b>    Bobigny<br />
                <b>SIRET:</b>    49298216000011<br />
                <b>N° TVA Intracommunautaire:</b>    FR05 492 982 160
              </p>
            footer_facture: |
              RIB : CL Paris 00460 - 30002 - 00460 - 0000006527D - 46/ IBAN - FR55 - 3000 - 2004 - 6000 - 0000 - 6527 - D46

            body:
                bon_de_commande: |
                  Bonjour,<br/><br/>
                  Comme convenu je vous fait parvenir la réservation à nous renvoyer avec la mention " bon pour accord" <br/><br/>
                  Cordialement<br/>
                  -- <br/>
                  <div>
                    <b><a href="http://www.facebook.com/pages/Maison-et-Devis/130308964191" target="_blank"><font color="#3366ff">Suivez nous sur facebook</font></a><br/>
                    </b><img src="http://www.maisondevis.net/website/facebook.jpg">&nbsp;&nbsp;<br><br>
                  </div>
                  Service commercial<br/>
                  Ligne directe : <a href="tel:%%2B33%%20%%280%%291.43.60.97.50" value="+33143609750" target="_blank">+33 (0)1.43.60.97.50</a><br/>
                  <a href="http://www.maisondevis.com/" target="_blank">www.maisondevis.com</a><br/>

                facture: |
                  Bonjour,<br/><br/>
                  Veuillez trouver ci joint votre facture correspondant à votre commande<br/><br/>
                  Cordialement<br/><br/>
                  Service comptabilité<br/>
                  Ligne directe : <a href="tel:%%2B33%%20%%280%%291.43.60.97.50" value="+33143609750" target="_blank">+33 (0)1.43.60.97.50</a><br/>
                  <a href="http://www.maisondevis.com/" target="_blank">www.maisondevis.com</a><br/>

                facture_proforma: |
                  Bonjour,<br/><br/>
                  Veuillez trouver ci joint votre facture correspondant à votre commande<br/><br/>
                  Cordialement<br/><br/>
                  Service comptabilité<br/>
                  Ligne directe : <a href="tel:%%2B33%%20%%280%%291.43.60.97.50" value="+33143609750" target="_blank">+33 (0)1.43.60.97.50</a><br/>
                  <a href="http://www.maisondevis.com/" target="_blank">www.maisondevis.com</a><br/>

        aj:
            mail_sender:                    "allojfr@gmail.com"
            mail_reply_to:                  "allojfr@gmail.com"
            mail_receiver_cc:               "allojfr2@gmail.com"
            object_mail:
                bon_de_commande:            "BDC alloj"
                facture:                    "Facture alloj"
                facture_proforma:           "Facture PF alloj"
            options:
                options1_label: Format
                options1_width: 89mm
                options1_property: format
                
                options2_label: Options
                options2_width: 61mm
                options2_property: options
                
                options3_label: Frais techniques
                options3_width: 152mm
                options3_property: frais
            header_facture: |
              <p>
                <b>EURL GAD - ALLOJ</b><br />
                CAP ST ANTOINE<br />
                155 RUE DE ROSNY<br />
                93100 MONTREUIL<br />
              </p>
              <p>
                <b>Tél:</b>      01.43.60.97.50<br />
                <b>Fax:</b>      01.43.60.97.50<br />
                <b>Capital:</b>  7 500 Euros<br />
                <b>R.C.S:</b>    Bobigny<br />
                <b>SIRET:</b>    49298216000011<br />
                <b>N° TVA Intracommunautaire:</b>    FR05 492 982 160
              </p>
            footer_facture: |
              RIB : CL Paris 00460 - 30002 - 00460 - 0000006527D - 46/ IBAN - FR55 - 3000 - 2004 - 6000 - 0000 - 6527 - D46

            body:
              bon_de_commande: |
                Bonjour,<br/><br/>
                Comme convenu je vous fait parvenir la réservation à nous renvoyer avec la mention " bon pour accord" <br/><br/>
                Cordialement<br/><br/>

                Service commercial<br/>
                Ligne directe : <a href="tel:%%2B33%%20%%280%%291.43.60.97.50" value="+33143609750" target="_blank">+33 (0)1.43.60.97.50</a><br/>
                <a href="http://www.alloj.fr/" target="_blank">www.alloj.fr</a><br/>

              facture: |
                Bonjour,<br/><br/>
                Veuillez trouver ci joint votre facture correspondant à votre commande<br/><br/>
                Cordialement<br/><br/>
                Service comptabilité<br/>
                Ligne directe : <a href="tel:%%2B33%%20%%280%%291.43.60.97.50" value="+33143609750" target="_blank">+33 (0)1.43.60.97.50</a><br/>
                <a href="http://www.alloj.fr/" target="_blank">www.alloj.fr</a><br/>

              facture_proforma: |
                Bonjour,<br/><br/>
                Veuillez trouver ci joint votre facture correspondant à votre commande<br/><br/>
                Cordialement<br/><br/>
                Service comptabilité<br/>
                Ligne directe : <a href="tel:%%2B33%%20%%280%%291.43.60.97.50" value="+33143609750" target="_blank">+33 (0)1.43.60.97.50</a><br/>
                <a href="http://www.alloj.fr/" target="_blank">www.alloj.fr</a><br/>

        rk:
          mail_sender:                    "allojfr@gmail.com"
          mail_reply_to:                  "allojfr@gmail.com"
          mail_receiver_cc:               "allojfr2@gmail.com"
          object_mail:
              bon_de_commande:            "BDC royal kosher"
              facture:                    "Facture royal kosher"
              facture_proforma:           "Facture PF royal kosher"
          options:
              options1_label: Format
              options1_width: 88mm
              options1_property: format
              
              options2_label: Activites
              options2_width: 58mm
              options2_property: activite
              
              options3_label: Date de sortie
              options3_width: 158mm
              options3_property: dateSortie
      
          header_facture: |
            <p>
              <b>ROYAL KOSHER</b><br />
              CAP ST ANTOINE<br />
              155 RUE DE ROSNY<br />
              93100 MONTREUIL<br />
            </p>
            <p>
              <b>Tél:</b>      01.43.60.97.50<br />
              <b>Fax:</b>      01.43.60.97.50<br />
              <b>Capital:</b>  7 500 Euros<br />
              <b>R.C.S:</b>    Bobigny<br />
              <b>SIRET:</b>    49298216000011<br />
              <b>N° TVA Intracommunautaire:</b>    FR05 492 982 160
            </p>
          footer_facture: |
              RIB : CL Paris 00460 - 30002 - 00460 - 0000006527D - 46/ IBAN - FR55 - 3000 - 2004 - 6000 - 0000 - 6527 - D46

          body:
            bon_de_commande: |
              Bonjour,<br/><br/>
              Comme convenu je vous fait parvenir la réservation à nous renvoyer avec la mention " bon pour accord" <br/><br/>
              Cordialement<br/><br/>

              Service commercial<br/>
              Ligne directe : <a href="tel:%%2B33%%20%%280%%291.43.60.97.50" value="+33143609750" target="_blank">+33 (0)1.43.60.97.50</a><br/>
              <a href="http://www.royalkosher.fr/" target="_blank">www.royalkosher.fr</a><br/>
      
            facture: |
              Bonjour,<br/><br/>
              Veuillez trouver ci joint votre facture correspondant à votre commande<br/><br/>
              Cordialement<br/><br/>
              Service comptabilité<br/>
              Ligne directe : <a href="tel:%%2B33%%20%%280%%291.43.60.97.50" value="+33143609750" target="_blank">+33 (0)1.43.60.97.50</a><br/>
              <a href="http://www.royalkosher.fr/" target="_blank">www.royalkosher.fr</a><br/>

            facture_proforma: |
              Bonjour,<br/><br/>
              Veuillez trouver ci joint votre facture correspondant à votre commande<br/><br/>
              Cordialement<br/><br/>
              Service comptabilité<br/>
              Ligne directe : <a href="tel:%%2B33%%20%%280%%291.43.60.97.50" value="+33143609750" target="_blank">+33 (0)1.43.60.97.50</a><br/>
              <a href="http://www.royalkosher.fr/" target="_blank">www.royalkosher.fr</a><br/>